### ISSUE TITLE
Embedded player give error and doesn't show when chrome security feature in enabled

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#151]
**Describe the bug (required)**
When livepeer.tv is embedded in an external html page the player does not show if chrome's setting "third-party scripts cookies are disallowed" is enabled. Instead the embedded player is just black.

**Expected behavior (required)**
The player is expected to show what is playing at [livepeer.tv](https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014)

**To Reproduce (required)**
- Enable chrome's security setting "third-party scripts cookies are disallowed".
- Make sure a video is playing a [livepeer.tv](https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014).
- Embed the media player in an external html page.
- Look at the console output.

**Device (required):**
- Google Chrome
 
**Screenshots (optional)**
# Getting
![embedded-player-chrome-error](https://user-images.githubusercontent.com/10135939/42594864-1360a502-8516-11e8-8a04-2763cc58d920.png)

**Console logs (optional)**

"Unhandled promise rejection DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document at createApolloCache (http://localhost:3000/static/js/bundle.js:190302:26)
at _callee5$ (http://localhost:3000/static/js/bundle.js:190186:25)
at tryCatch (http://localhost:3000/static/js/bundle.js:11443:40)
at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:11677:22)
at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:11495:21)
at step (http://localhost:3000/static/js/bundle.js:11075:30)
at http://localhost:3000/static/js/bundle.js:11086:13
at run (http://localhost:3000/static/js/bundle.js:20920:22)
at http://localhost:3000/static/js/bundle.js:20937:30
at MutationObserver.flush (http://localhost:3000/static/js/bundle.js:19501:9)"

**Additional context (optional)**
Some research led me to [this solution](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document).

It seems that when chrome settings enable "third-party scripts cookies are disallowed", then access to localStorage may result in thrown SecurityError exceptions.

The problem here with the embedding is that it is trying to write to the user's browser local storage which chrome doesn't allow by default. Using another browser such as Firefox does not give this error.

**Comment by Randy1Burrell** [comment]
Closing this.
