### ISSUE TITLE
Explorer account info not loading consistently

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#256]
**Describe the bug (required)**
The explorer has been acting erratic for me: my account information doesn't always load across various pages (transcoder, account overview, 'delegating' tab, etc).

**Expected behavior (required)**
Account information to load quickly and consistently.

**To Reproduce (required)**
1. Go to explorer.livepeer.org
1. Sometimes the "My Account" button doesn't show. I can't see the "Bond" button on the transcoders, my delegation dashboard is empty, etc. Sometimes they show up after awhile, but not always.

**Device (required):**
Chrome, OSX 

**Console logs (optional)**
Note that it is difficult to capture the console logs; the page seems to reload frequently, which throws tons of exceptions, and the debugger blocks the rest of the UI. But I'm not a Chrome dev console guru.
```
main.251bc047.js:1 Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.251bc047.js:1
(anonymous) @ main.251bc047.js:1
21:52:49.085 main.251bc047.js:1 Unhandled GraphQL subscription error Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.251bc047.js:1
error @ main.251bc047.js:1
21:52:49.085 main.251bc047.js:1 Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.251bc047.js:1
(anonymous) @ main.251bc047.js:1
21:52:49.086 main.251bc047.js:1 Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.251bc047.js:1
(anonymous) @ main.251bc047.js:1
21:52:49.130 main.251bc047.js:1 Uncaught Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.251bc047.js:1
21:52:49.131 main.251bc047.js:1 Uncaught Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.251bc047.js:1
21:53:28.041 main.251bc047.js:1 Unhandled error GraphQL error: [ethjs-rpc]  error with payload {"id":287602123758,"jsonrpc":"2.0","params":[{"from":"0x867c90a7f48fb39b2f3ccbdd33e5002477b935ae","gas":"0x200b20","to":"0x","data":"0x70a08231000000000000000000000000867c90a7f48fb39b2f3ccbdd33e5002477b935ae"},"latest"],"method":"eth_call"} Error: JsonRpcEngine - response has no error or result for request:
{
  "id": 1896221456,
  "jsonrpc": "2.0",
  "params": [
    {
      "from": "removed",
      "gas": "0x200b20",
      "to": "0x",
      "data": "0x70a08231000000000000000000000000867c90a7f48fb39b2f3ccbdd33e5002477b935ae"
    },
    "latest"
  ],
  "method": "eth_call"
} Error: GraphQL error: [ethjs-rpc]  error with payload {"id":287602123758,"jsonrpc":"2.0","params":[{"from":"0x867c90a7f48fb39b2f3ccbdd33e5002477b935ae","gas":"0x200b20","to":"0x","data":"0x70a08231000000000000000000000000867c90a7f48fb39b2f3ccbdd33e5002477b935ae"},"latest"],"method":"eth_call"} Error: JsonRpcEngine - response has no error or result for request:
{
  "id": 1896221456,
  "jsonrpc": "2.0",
  "params": [
    {
      "from": "removed",
      "gas": "0x200b20",
      "to": "0x",
      "data": "0x70a08231000000000000000000000000867c90a7f48fb39b2f3ccbdd33e5002477b935ae"
    },
    "latest"
  ],
  "method": "eth_call"
}
    at new t (https://explorer.livepeer.org/static/js/main.251bc047.js:1:373298)
    at https://explorer.livepeer.org/static/js/main.251bc047.js:1:1077373
    at https://explorer.livepeer.org/static/js/main.251bc047.js:1:1084346
    at Array.forEach (<anonymous>)
    at https://explorer.livepeer.org/static/js/main.251bc047.js:1:1084326
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1084233)
    at Object.next (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1085017)
    at v (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1031112)
    at m (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1031616)
e._subscription.e._subscription._observer.e._subscription._observer.error.e._subscription._observer.error @ main.251bc047.js:1
21:53:28.041 main.251bc047.js:1 Unhandled error GraphQL error: Cannot read property 'name' of undefined Error: GraphQL error: Cannot read property 'name' of undefined
    at new t (https://explorer.livepeer.org/static/js/main.251bc047.js:1:373298)
    at https://explorer.livepeer.org/static/js/main.251bc047.js:1:1077373
    at https://explorer.livepeer.org/static/js/main.251bc047.js:1:1084346
    at Array.forEach (<anonymous>)
    at https://explorer.livepeer.org/static/js/main.251bc047.js:1:1084326
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1084233)
    at Object.next (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1085017)
    at v (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1031112)
    at m (https://explorer.livepeer.org/static/js/main.251bc047.js:1:1031616)
e._subscription.e._subscription._observer.e._subscription._observer.error.e._subscription._observer.error @ main.251bc047.js:1
21:53:46.406 delegating:1 Failed to load resource: the server responded with a status of 403 ()
```

**Comment by Randy1Burrell** [comment]
@j0sh did you upgrade your MeteMask recently?

**Comment by j0sh** [comment]
My MetaMask certainly isn't what it used to look like, but I'm not sure when it was updated. Within the last few months for sure. I haven't used the explorer in a little while, so that might be related.

**Comment by Randy1Burrell** [comment]
@j0sh I think the security update that MetaMask put in effect this week is what is causing the explorer to react that way. I merged a PR from @ya7ya this week that I hope will fix this but I am still looking into other opportunities to get around it.

**Comment by Randy1Burrell** [comment]
@j0sh the latest deployment have fixed some of the instability issues within the explorer, but not all. I am looking into what is causing the errors in the console. Can you please let me know if you find any other issue?

**Comment by dob** [comment]
In Chrome I'm consistently seeing data fail to fetch/load. For example even the round indicator is grey, as if it can't tell what round we're in, if it's initialized or not. It is also failing to load any data on the transcoders page.
